### ISSUE TITLE
Decade selector generates wrong query

### ISSUE THREAD

**Issue by christopheryork** [cfrp-laval/analytics#12]
The generated query includes one year of the following decade: i.e. 1-1-1710 to 31-12-1750.  (Should be 1-1-1710 to 31-12-1749.)

![image](https://cloud.githubusercontent.com/assets/2471299/20029676/ca1fa734-a34a-11e6-9b9f-b7796cf4bdca.png)

**Comment by hspier** [comment]
@christopheryork Are the period selector expected to behave as 
- Between the two selected dates ?
- Between and including the "to" date ?
I don't mind changing the range, just wanted to get a little background.

**Comment by hspier** [comment]
Also, I realised that in the code the upper value is December 30 and not December 31; I have a fix coming in.

**Comment by christopheryork** [comment]
Hi Hugo - Perhaps best to check with the Laval designer for what he/she intended here.

My own sense is that the range selector for dates only makes sense when the FROM and TO fields are specific days, and never otherwise.

That's because:

(a) you can select a range of decades or years by filtering on the decades or years dimension - so the basic functionality already exists.  If the problem is that users want to filter results on a given dimension without aggregating values on that dimension, we can arrange for the webservice to accept these queries and give the right result fairly easily.

(b) the natural breaking point between years for the Comédie Française is Easter, when the troupe took vacation. (i.e. adding values up from Jan 1 to Dec 31 combines two CF seasons into one, which makes no sense).

**Comment by Guliavan** [comment]
I originally only put the years in the date selector to come with a quick and easy solution given the time I had. This wasn't analyzed in detail from a designer. I was also told this would answer the users need after having discussed with Sara and Bertrand. 

I don't know if it has changed, but I think you should check with Bertrand about it and see what would be the priority. Also, I don't think there is a designer working on the team anymore, but you may confirm with Bertrand.

**Comment by hspier** [comment]
I asked Bertrand for the actual ask, but you are right Christopher, the dates should be adjusted to match the breaking points.

Therefore, choosing a period between 1710 to 1750 would be expressed as: 
April 1st 1710 to March 31st 1750

Does that makes sense ?

**Comment by blirette** [comment]
Good point guys. I'm leaning toward Hugo's answer, but will clarify with Sara just to be sure. I'll get back to you on that soon.

**Comment by christopheryork** [comment]
Hugo, I agree with you: it's more intuitive to include the end of the range.  So decades 1710-1750 should mean 1710-1759.

The backend uses calendar years (unless "seasons" is the dimension).  To match it, provide 1 Jan 1710-31 Dec 1759.  

Personally I think this is a good reason to ask the user to set month and day for a date range: then it's the user's choice.

It's a vexed issue generally: this is why the calendar shows 14 months for each season, so Easter can move on each end.  Sara will know the best fit for CF's data.

**Comment by blirette** [comment]
Got Sara's answer: even tought it's not right for every year, we'll go with April 1st 1710 to March 31st 1750. Thanks!

**Comment by christopheryork** [comment]
This recapitulates the original problem.  You need to choose a date that coincides with a decade, not one year into a decade.
