### ISSUE TITLE
Rounding numbers aren't applied properly

### ISSUE THREAD

**Issue by blirette** [cfrp-laval/analytics#13]
It seems the sum isn't being appropriately calculated.
Second line sum doesn't add up. Guess it's missing some number rounding. Should be 22244. Thanks for looking into it!
![image](https://cloud.githubusercontent.com/assets/1894507/20760268/8a0c5c30-b6ed-11e6-80de-955f563182f3.png)

**Comment by christopheryork** [comment]
It appears the current crosstab table code uses toFixed(0) to format numbers (e.g. here: https://github.com/cfrp-laval/analytics/blob/e53cd206bb48921acf0fa5a1f552051d99d3f219/js/crosstab.js#L120).

Instead it should use the i18n framework in js/cfrp-schema.js, which specifies language-specific formatters for all dimension and aggregate values.  An example:

```
var schema = require('../cfrp-schema')
...
var fmt = schema.format('fr', 'sum_receipts')  // or usually "schema.format(lang, query.agg)"
var s = fmt(22243.5)
> "22,243.50"
```

The formatters for CFRP are defined here:  https://github.com/cfrp-laval/analytics/blob/e53cd206bb48921acf0fa5a1f552051d99d3f219/cfrp-schema.js#L142-L207

Once the table is fixed, you can use a different precision for receipts sums throughout the application by changing this line: https://github.com/cfrp-laval/analytics/blob/e53cd206bb48921acf0fa5a1f552051d99d3f219/cfrp-schema.js#L174-L175

The formats are standard d3 number specifiers: see https://github.com/d3/d3-3.x-api-reference/blob/master/Formatting.md

format(',.2f') is a reasonable choice.
