### ISSUE TITLE
Latency in all queries

### ISSUE THREAD

**Issue by blirette** [cfrp-laval/analytics#15]
The tool in dev area seems to be way slower now then before. Changed anything? It seems to be more of a client side problem since the tool on my computer was way faster than the one on Sara's computer (2010 laptop vs. mine of 2013). @hspier

**Comment by hspier** [comment]
Which tool are you referring to ?

**Comment by blirette** [comment]
Phase 2 tool in the dev area. It's the only one I can use and is online. (cfrp-laval.github.io/analytics/)

**Comment by hspier** [comment]
Looking at the tool, I am seeing some queries for the calendar, but these queries were there before I started the modification; I already fixed that issue though on my computer now that I have started activating the calendar, so I will push a change tonight; let me know if it goes faster after that.

**Comment by hspier** [comment]
I have put a fix for the calendar queries taking all the time, let me know if this has fixed the issue. Another potential problem I could think of (if it's not fixed) are the foundation tooltips.

**Comment by christopheryork** [comment]
@hspier @blirette, if profiling determines the calendar is cause for any delays, there are two possible optimisations:

**Comment by blirette** [comment]
It seems the latency is gone. Thanks!
