### ISSUE TITLE
Display an alert when there's 20 filters or more on the X or Y axis.

### ISSUE THREAD

**Issue by blirette** [cfrp-laval/analytics#21]
Display an alert when there's 20 filters or more on the X or Y axis.

Is it too heavy to implement? Let's talk.

![image](https://cloud.githubusercontent.com/assets/1894507/21898781/fc21d026-d8bb-11e6-816b-9add0093dfff.png)

**Comment by hspier** [comment]
@blirette As the graph (the chart) is actually used to render an image, why are we allowing to download it (from the icon link) if we prevent from displaying it? There are chances the image will not be clearer. Is the intent of the button to download the CSV instead?
Also, is it a problem if the link to download is a button inside the alert instead? I am reusing the window that is displayed when switching to the calendar view.

**Comment by hspier** [comment]
I am attaching a screenshot of what I have right now (I am ready to commit).

![image](https://cloud.githubusercontent.com/assets/6555494/22087867/7e0e46d6-ddae-11e6-80ea-0281ed2bff6b.png)

**Comment by blirette** [comment]
The goal is to alert the user they'll probably won't be able to see all the data being represented on the graph. Then, we still want them to be able to download both CSV and graph as usual.

**Comment by blirette** [comment]
I don't see the message showing in the staging area (http://cfrp-laval.github.io/analytics/). Let me know when it'll be done @hspier. Thanks!

**Comment by hspier** [comment]
The fix is in staging, but it is missing the download of the graph. Right now only the CSV can be downloaded. I will add the graph download in next wave of push.
