### ISSUE TITLE
"Nouvelle recherche" button is making the app go mad (http://cfrp-laval.github.io/analytics/)

### ISSUE THREAD

**Issue by blirette** [cfrp-laval/analytics#25]
When you use the "Nouvelle recherche" button, the app seems to call a bad API or DB since labels like "Total des sommes" change for "Total des sommes (pondérés)" and cause the app to misbehave.

Either change the so it works properly or make it do a browser page "refresh" (the same as using F5).

**Comment by jamiefolsom** [comment]
What should clicking 'nouvelle recherche' do? Currently, it sends a request for a sum of all receipts by decade. Also, that label is in the translation file for the UI, [here](https://github.com/cfrp-laval/analytics/blob/2ed83a4c9c898f05f97db6f6c5b0021ce99da3e5/i18n/query.json#L100). Should that be changed? I think this is all front end work -- changing either the request to be sent upon click, or how the UI updates subsequently.

**Comment by blirette** [comment]
Ok, I'll let @hspier check that one out too.

**Comment by hspier** [comment]
Fixed in staging

**Comment by blirette** [comment]
@hspier : @hspier Doesn't seem to reset the X axis filters (probably the same for the Y filters):
![1](https://user-images.githubusercontent.com/1894507/31718271-4708b67a-b3dd-11e7-9ba8-eddf3c8415e3.png)
![2](https://user-images.githubusercontent.com/1894507/31718275-4928de76-b3dd-11e7-953a-8f9bd4447097.png)

**Comment by hspier** [comment]
Fixed the issue in staging
