### ISSUE TITLE
"Actes" labels aren't ok (http://cfrp-laval.github.io/analytics/)

### ISSUE THREAD

**Issue by blirette** [cfrp-laval/analytics#28]
(http://cfrp-laval.github.io/analytics/)

The "Actes" labels aren't ok. They should use similar labels as "Genres".

Ask if you need explaining on that.

**Comment by blirette** [comment]
Instead of this:
![image](https://user-images.githubusercontent.com/1894507/30983258-e13746c0-a457-11e7-8cac-d75634aedea0.png)
...we should see this:
Actes
Actes de la première pièce
Actes de la seconde pièce
Actes de la troisième pièce

And for this:
![image](https://user-images.githubusercontent.com/1894507/30983279-f8b68950-a457-11e7-9db4-9e04dbb91a68.png)
... we should only see the options 1, 3, 5 and leave the blank option.

To my understanding, this can all be done by @hspier so I'll remove Jaime from the issue.
Thanks!

**Comment by hspier** [comment]
Fixed on staging.

**Comment by blirette** [comment]
@hspier : Doesn't seem to reset the X axis filters (probably the same for the Y filters):
![1](https://user-images.githubusercontent.com/1894507/31718190-ea6b6f20-b3dc-11e7-8fe7-a7ab5d03c11d.png)
![2](https://user-images.githubusercontent.com/1894507/31718193-ece144fa-b3dc-11e7-83a9-c0bbf838c200.png)

**Comment by hspier** [comment]
@blirette Just realized that I missed the second part.
